### ISSUE TITLE
New release with sensitive input?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/steps-codecov#15]
I see master has marked the input as sensitive, however there's no new release.

- https://github.com/bitrise-io/steps-codecov/commit/b4a7715b6b80f69b8eb39ea4ff432f0a08f19ea1

1.1.4 is still the latest from 2017
https://github.com/bitrise-io/steps-codecov/releases

**Comment by bootstraponline** [comment]
Also the primary use case of codecov is to report code coverage on pull requests pre-merge. Is that compatible with the secrets model of Bitrise?

**Comment by trapacska** [comment]
Thank you for the feedback. The step is just released now.

Sensitive input question for the input itself, if it contains sensitive data then it is sensitive input, no matter where or what the step does.
