### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by guitcastro** [bitrise-io/steps-codecov#2]
This step works for Android as well, but it's no possible to add it to my workflow because of the `host_os_tags` and `project_type_tags`. I have created a [Android step](https://github.com/guitcastro/codecov-android), but talking with the folks from CodeCov they recommend to use the bash script instead of the python. So I think we can use this steps for both platforms.

**Comment by viktorbenei** [comment]
Thanks for the feedback! Are you sure that the bash script can work on Linux too? I guess it can, my question is more like: did you try that? ;)

**Comment by guitcastro** [comment]
@viktorbenei Yep! I am using it in my workflow (as script step)

**Comment by viktorbenei** [comment]
all right, I'll do the required change and push a new version of the step tomorrow! Thanks for the info & suggestion! ;)

**Comment by viktorbenei** [comment]
Done & published in v1.0.1 - thanks for the suggestion! 😉

**Comment by guitcastro** [comment]
@viktorbenei Nice!, now we have to deprecate my step. How can I proceed with that ?

**Comment by viktorbenei** [comment]
We just introduced this in Bitrise CLI 1.3.x - you have to send a Pull Request into the StepLib, adding a `step-info.yml` into your step's directory, with a deprecation note and date. Please pick a reasonable removal date, like 3-6 months, unless it's critical to have it removed sooner.

Example `step-yml` with removal notice: https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/bitrise-artifact-deploy/step-info.yml
