### ISSUE TITLE
Cant ignore Pods directory

### ISSUE THREAD

**Issue by Stoff81** [bitrise-io/steps-codecov#7]
Hey guys,

Im really struggling to ignore the Pods directory for the coverage stats. Im using XCode with Swift.
Ive tried adding the ```-J "ProjectName" in bitrise config although the Pods dir still comes up in the coverage.

Any ideas?

**Comment by viktorbenei** [comment]
Hi,

I think you should ask this from the codecov guys, this is all what the step does: https://github.com/bitrise-io/steps-codecov/blob/master/step.sh

**Comment by stevepeak** [comment]
@Stoff81 If the `-J` does not work (which is should 😄 ) Then you can also ignore pods in a codecov.yml file:

```yaml
# filename: codecov.yml
ignore:
  - "Pods/"
```

**Comment by viktorbenei** [comment]
Thanks @stevepeak , I wasn't aware that you watch the issues here ;)
