### ISSUE TITLE
No coverage report found.

### ISSUE THREAD

**Issue by dmytrodanylyk** [bitrise-io/steps-codecov#8]
I have added "Codecov.io token" and "Additional options for Codecov call" remains empty.

Here are logs:

```
==> Bitrise CI detected.
    project root: .
--> token set from env
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ! | codecov@1.1.3 (exit code: 1)                                  | 1.94 sec |
``` 

As you can see logs says: `No coverage report found.`

Before launching codecov task I launch my task `javaCodeCoverage` which generate jacoco report and I am able to deploy jacoco generated report `.html` file.

```
apply plugin: 'jacoco'

task javaCodeCoverage(type: JacocoReport, dependsOn: 'testDevDebugUnitTest') {

    reports {
        xml.enabled = false
        html.enabled = true
        html.destination "$project.buildDir/outputs/jacoco/"
    }

    def classFileTree = fileTree(
            dir: "${buildDir}/intermediates/classes/dev/",
            excludes: [ ... ],
            includes: [ ... ]
    )

    classDirectories = files([classFileTree])
    sourceDirectories = files("${project.projectDir}/android/src/main/java")
    executionData = files("${buildDir}/jacoco/testDevDebugUnitTest.exec")
}
```

**Comment by viktorbenei** [comment]
Hi @dmytrodanylyk ,

You should contact the codecov support about this, this is all what this step does:

https://github.com/bitrise-io/steps-codecov/blob/master/step.sh

It just downloads the codecov bash script and runs it (and interprets the script's exit code).

**Comment by stevepeak** [comment]
Hey @dmytrodanylyk this is an issue with generating the reports. I see your message in Intercom and I'll reply there. Thank you.

**Comment by dmytrodanylyk** [comment]
The issue was that I have turned off generating .xml report file. After turning it on everything worked as it should.

**Comment by viktorbenei** [comment]
Thanks for reporting @dmytrodanylyk ! ;)

**Comment by viktorbenei** [comment]
And of course thanks @stevepeak for the help :)

**Comment by Anurag--Singh** [comment]
> The issue was that I have turned off generating .xml report file. After turning it on everything worked as it should.

@dmytrodanylyk How did you turned on generating .xml report file?

**Comment by huxaiphaer** [comment]
@dmytrodanylyk , how did you turn it on?

**Comment by fehersanyi-bitrise** [comment]
@huxaiphaer @Anurag--Singh 
I'm pretty sure that it is a config on codecov.io

**Comment by huxaiphaer** [comment]
Thanks so much @fehersanyi-bitrise , I got to know why I had this problem, I had not set the token number of `codecove` in the `.travis.ym`l file.
